---
title: "ECON4538 - Syllabus"
bibliography: reading_list.bib
author: Prof. Joseph Mullins
format:
    pdf:
        colorlinks: true
---

This is an advanced undergraduate course in Labor Economics. Please read below for the course outline and syllabus.

## Class Times

### Lectures

Mondays and Wednesdays, 9:45am - 11am, Blegen Hall 240

### Recitations

Fridays, 10:10am - 11am, Blegen Hall 215

## Email and Office Hours

You will find details on how to contact me and sign up for office hours on the [course Canvas page](https://canvas.umn.edu/). 


## Course Overview and Objectives

In this class we will address questions at the forefront of modern economic policy. What factors drive economic inequality over the life-cycle? How are these evolving over time? What are the potential costs and benefits to collective provision of insurance and redistribution? What policies are effective in creating equal opportunity? 

To answer these questions you will learn the basic tools of modern quantitative economics. We will be interested in understanding the models and tools that economists have developed to understand labor market inequality, as well as in using these models to analyze the welfare implications of various government interventions. Topics to be covered include: dynamic programming, solution methods of general equilibrium models, heterogeneous-agent macroeconomic models, models of human capital formation, and modern empirical evidence on the nature human capital.


## Student Learning Outcomes

On successfully completing this course, students should be familiar with some of the core concepts in modern quantitative economics. Students should be able to formalize an appropriate dynamic, stochastic, general equilibrium model to analyze a question of interest. Students should be able to solve and simulate such a model on a computer, for the purpose of interpreting data and conducting policy experiments.

## Course Prerequisites

I will assume that you are comfortable with micro concepts at the level of Econ 3101, 3102, such as the utility maximization problem and its related topics. I will also assume that you are comfortable with basic econometrics such as multivariate regression techniques as well as statistics at the level of Stat 3011. With regards to your math background, I will take as granted that you know how to work with calculus (derivatives). Students should be willing to invest time in learning a computer programming language such as `julia`.

## Textbook

We will use some chapters and problem sets from *Recursive Macroeconomic Theory* [@Ljungqvist2012,  3rd edition] available online via the University Library.  We will also make use of Journal Articles. I have provided links to electronic versions of the textbook and journal articles are available on the "Library Course Page". 

### Additional Readings

You may also find some of the following books useful.

- John Stachurski, Economic Dynamics: Theory and Computation, 2nd edition, (2022).
- Christopher Pissarides, Equilibrium Unemployment Theory, 2nd edition, (2000).
- Jérôme Adda and Russell Cooper, Dynamic Economics: Quantitative Methods and Applications, (2003).
- Mario Miranda and Paul Fackler, Applied Computational Economics and Finance, (2002).
- Kenneth Judd, Numerical Methods in Economics, (1998).

## Course Software and Resources

We will demonstrate and develop the computational tools you are learning using the `julia` programming language, which is well-suited for scientific computation and data analysis. LATIS provides a copy of `julia` on AppstoGo, but we recommend installing your own version, since it is completely free and open source. [See the website](https://julialang.org/) for more details on the language and installation instructions.

Throughout the course, you may find the [QuantEcon](https://julia.quantecon.org/intro.html) `julia` course (by Tom Sargent, John Stachurski, and Jesse Perla) a useful additional resource.

## Assessment

The course will be graded based on 6 problem sets (each worth 7%, 42% total), a midterm exam (20%), and a final exam (38%).

### Submission Guidelines

It is your responsibility to submit neat and legible solutions to the problem sets. Your TA may deduct marks for illegible submissions. Please follow these guidelines:

- All homework assignments must be submitted as a `Quarto` or `jupyter` notebook rendered as an html or pdf, with code and output showing all required results. You will be introduced to these notebooks through recitation materials.
- For questions requiring mathematical solutions, you may submit handwritten solutions if you prefer, but they must be submitted as a pdf using a scanner or scanning app on your phone.

## Course Outline

### Dynamic Programming and Applications 

An important set of mathematical tools for solving dynamic models. Topics include:

- Bellman's principal of optimality and contraction mappings
- Mathematical and computational exposition (using julia) of dynamic programming tools, applied to:
    - Models of job search
    - Infinite horizon and life-cycle models of savings

**Reading**: @Ljungqvist2012 Chapters 3-6.

### Savings and incomplete markets

Review of the main theoretical models describing savings and self-insurance of agents under uncertainity and incomplete markets.

- Main savings problems
- Incomplete markets models as @Huggett1993, @aiyagari1994, @krusell1998
- Consumption inequality and income uncertainity.

**Reading**: @Ljungqvist2012 Chapters 17-18. @Deaton1991, @blundell1998, @Huggett1993, @aiyagari1994, @krusell1998

### Facts about Inequality 

We review and replicate facts about labor market inequality in the United States. Topics include:

- Documenting income inequality [@moffitt2011; @Heathcote2010; @Heathcote2023; @Guvenen2021]
- Estimation of income risk [@moffitt2011; @Meghir2004; @Low2010; @Guvenen2009]
- Welfare implications of income inequality [@Storesletten2004]
    - Redistribution vs Insurance
- The Intergenerational Elasticity of Earnings [@corak2013; @mazumder2018]
- Skills and Inequality [@Heckman2006; @Cunha2008a; @Cunha2009]

### Theories of Human Capital and Inequality

We introduce textbook theories of human capital formation and examine their empirical content. We develop computational tools to bring these theories to data. Topics include:

- The Becker-Tomes model of intergenerational inequality via human capital investment [@Becker1979; @Becker1986]
    - Policy implications of the model (efficiency and redistribution)
- Debates on the empirical and conceptual merits of the Becker-Tomes model [@Goldberger1989; @Mulligan1999; @Cunha2006; @Cunha2007]
- Quantitative and theoretical extensions of the baseline model [@Lee2019; @Caucutt2020]

### Connecting Human Capital Theory with Evidence

We survey some empirical work that connects the theory with data. Topics include:

- A review of econometric methods for causal inference
- Evidence of the effect of social programs on child skill formation and long-run outcomes [@Dahl2012; @Barr2022; @Bastian2018; @Carneiro2021; @bailey2024; ]
- Evidence of the effect of early childhood education on skill formation and long-run outcomes [@heckman2010; @Garcia2020; @Kline2016]
- Evidence of the effect of parenting and home interventions on skill formation and long-run outcomes [@ATTANASIO2020; @Walker2022; @Carneiro2024]
- Estimating the technology of skill formation. [@Cunha2008b; @ATTANASIO2020]

## Grading, Policies, and Procedures

Please see the course Canvas page for the department grading scale and a statement of University policies and procedures.