---
title: "Syllabus"
bibliography: ../reading_list.bib
format:
  revealjs:
    theme: solarized
    transition: slide
    chalkboard:
        theme: whiteboard
        chalk-effect: 0.0
        chalk-width: 6
---

# Course Outline

## Facts About Inequality {.smaller}


:::{.incremental}
- Some basic facts about labor market inequality @Heathcote2023
- Thinking through policy implications (*redistribution* vs *insurance*) 
- Estimating income processes 
    - How much income risk do workers face? How much is realized before labor market entry?
- Intergenerational income inequality
    - How much inequality is *inherited from birth*?
- Skills and inequality
    - How much inequality can be explained by measured skills and traits?
    - *Latent factor models*
:::

## The Human Capital Framework

:::{.incremental}
- Intergenerational dynamics and efficiency [@Becker1979; @Becker1986]
    - Empirical content of model. Does it fit the data?
- Quantitative modeling exercises
    - Use our **dynamic programming tools**
:::

## Connecting the Framework with Data
:::{.incremental}
- A review of econometric methods for causal inference
- Effect of social programs (Medicaid, Food Stamps, EITC)
- Early childhood education
- Parenting and home interventions
- Estimating the *technology of skill formation*
:::

# Some Admin / Other

## Assessment

:::{.incremental}
- 3 problem sets (due dates on Canvas)
    - theory + coding
    - will provide examples in recitation to scaffold
    - use genAI as much as you want, but...
- Final
    - **December 15, Blegen  240, 10:30am - 12:30pm**
    - theory **and** coding questions (will provide examples)
    - so make sure you use the problem sets to learn
:::

## Lectures and Learning

:::{.incremental}
- I will make slides available as soon as I have them
- They are **not** a substitute for attendance
- We will do theory and exercises "on the board"
- The reading list is intended to supplement for those interested in going deeper
    - Unless stated otherwise, you only need what we cover in class
:::

## Online Class Dates
<!-- 2025: in Australia, November 3rd on zoom -->

## Citations